version: '3'

services:
  api-restaurante:
    build:
      context: ./api-restaurante
    ports:
      - "8000:8000"
    volumes:
      - ./api-restaurante:/var/www/html
    networks:
      - restaurante-network
  front-restaurante:
    build:
      context: ./front-restaurante
    ports:
      - "3000:3000"
    volumes:
      - ./front-restaurante:/app  # Mount local directory to containe

  restaurante-db-migrations:
    image: mysql:8.0
    #container_name: mysql-base
    #restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: restaurante
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "UTC"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - restaurante-network
volumes:
  mysql_data:

networks:
 restaurante-network:
  driver: bridge

 #db:
  #  image: mysql:latest
   # container_name: mysql
    #restart: unless-stopped
    #environment:
     # MYSQL_ROOT_PASSWORD: example_password
      #MYSQL_DATABASE: your_database_name
      #MYSQL_USER: your_database_user
      #MYSQL_PASSWORD: your_database_password
    #ports:
     # - "3306:3306"
    #volumes:
    #  - mysql_data:/var/lib/mysql